Reference for this  page: https://www.youtube.com/watch?v=aYmcRnmZVGQ&list=PL9n0l8rSshSnragNblKDBsT8Xu3otp3jA&pp=iAQB 

In [1]:
import numpy as np

In [2]:
#Python List
lst=[1,[1,3,5],35,'test', False, 0.4]
print(lst)

#Numpy Array
array=np.array([1,3,4,5])

#* The primitive types supported are tied closely to those in C language.
#! Differences between list and ndarray: 
#? 1.Datatypes of elements in a list could be mixed, in an np.array should be homogenous
#? 2.Once created the size of the  list can be changed, but the size of the np.array is fixed
#? 3.Lists are dynamic, np.array are static
#? 4.Lists are slower than np.array, np.array are faster than lists
#? 5.Lists are more memory efficient than np.array, np.array are less memory efficient
#? 6.Lists have limited dimensional  support, np.array have	built-in multidimensional support

[1, [1, 3, 5], 35, 'test', False, 0.4]


In [3]:

print('1D array')
a=np.array([1,3,5])
print(a)

print('2D array')
b=np.array([[1,2,4,4],[3,4,6,7],[5,5,6,0]])
#!it must be a mxn matrix
#b=np.array([[1,2],[3,6,7],[5,5,6,0]]) #!this is not a mxn matrix so its  not allowed
print(b)


1D array
[1 3 5]
2D array
[[1 2 4 4]
 [3 4 6 7]
 [5 5 6 0]]


shape returns a tuple of  two values: the first stands for the rows in an array, and the second for the number of column
(rows, cols)

In [4]:
print(a.shape)
print(b.shape)

(3,)
(3, 4)


size returns the total number of elements in an array

In [5]:
print(a.size)
print(b.size)

3
12


dtype: datatype of elements in the  array for the all types check the documentation

In [6]:
print(a.dtype)
print(b.dtype)

int64
int64


transpose(): replace columns with rows and rows  with columns

In [7]:
print('Before Transpose:\na= ', a)

print('Validation shape before transpose: ', a.shape)

print('After Transpose:\na=', a.transpose())

print('Validation shape after transpose: ', a.transpose().shape)

print('Before Transpose:\nb=', b)

print('Validation shape before transpose: ', b.shape)

print('After Transpose:\n b=', b.transpose())

print('Validation shape after transpose: ', b.transpose().shape)


#!b.transpose() doesnt change b as its value, to change the value of b, you must use  b=b.transpose()
#!a is a 1D array no difference between a and a.transpose()


Before Transpose:
a=  [1 3 5]
Validation shape before transpose:  (3,)
After Transpose:
a= [1 3 5]
Validation shape after transpose:  (3,)
Before Transpose:
b= [[1 2 4 4]
 [3 4 6 7]
 [5 5 6 0]]
Validation shape before transpose:  (3, 4)
After Transpose:
 b= [[1 3 5]
 [2 4 5]
 [4 6 6]
 [4 7 0]]
Validation shape after transpose:  (4, 3)


np.empty((rows, cols), dtype=datatype): create rowsxcols array with random values in each position, based on the datatype passed

In [8]:
c=np.empty((3,3),  dtype=int)
print('Random 3x3 array of integers\n',c)

d=np.empty((6,3),  dtype=bool)
print('Random 6x3 array of boolean\n',d)

e=np.empty((2,2),  dtype=float)
print('Random 2x2 array of float\n',e)


Random 3x3 array of integers
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
Random 6x3 array of boolean
 [[ True  True  True]
 [ True  True  True]
 [False False False]
 [False False False]
 [False False False]
 [False  True False]]
Random 2x2 array of float
 [[9.79830996e+252 4.61964766e+281]
 [3.17095857e+180 2.59345444e+161]]


np.ones((rows, cols), dtype=datatype) : Initialize a rowsxcols array with ones the dtype is not required it just specifies what type is needed (by default is float)

In [9]:
f=np.ones((3))
print('array of ones\n',f)

g=np.ones((3,6))
print('3x6 array of ones\n',g)

h=np.ones((3,4), dtype=int)
print('3x4 array of int ones\n',h)

i=np.ones((3,4), dtype=str)
print('3x4 array of String ones\n',i)

array of ones
 [1. 1. 1.]
3x6 array of ones
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
3x4 array of int ones
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
3x4 array of String ones
 [['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


np.zeros((rows, cols), dtype=datatype) : Initialize a rowsxcols array with zeros the dtype is not required it just specifies what type is needed (by default is float), if string it take it as an empty string

In [10]:
j=np.zeros((3))
print('array of zeros\n',j)

k=np.zeros((3,6))
print('3x6 array of zeros\n',k)

l=np.zeros((3,4), dtype=int)
print('3x4 array of float zeros\n',l)

m=np.zeros((3,4), dtype=str)
print('3x4 array of string zeros\n',m)

array of zeros
 [0. 0. 0.]
3x6 array of zeros
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
3x4 array of float zeros
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
3x4 array of string zeros
 [['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


np.arange(start, end, step):  similar to range(start, stop, step) for lists, it creates an array starting from start,  stopping at end, and stepping by step.

default value of start is 0

default value of step is 1

In [11]:
arange=np.arange(1,20, 2) 
print('np.arange(1,20, 2): ',arange)

arange1=np.arange(10)
print('np.arange(10): ', arange1)

arange3=np.arange(1, 10)
print('np.arange(1, 10): ',arange3)

np.arange(1,20, 2):  [ 1  3  5  7  9 11 13 15 17 19]
np.arange(10):  [0 1 2 3 4 5 6 7 8 9]
np.arange(1, 10):  [1 2 3 4 5 6 7 8 9]


reshape((rows, cols)):   # Reshape the array to a rowsxcols array if possible 

size=rows x cols 

In [12]:
print('From', arange1)
reshape1=arange1.reshape((5,2))
print('Into\n',reshape1)

print('From', arange3)
reshape=arange3.reshape((3,3))
print('Into\n',reshape)

From [0 1 2 3 4 5 6 7 8 9]
Into
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
From [1 2 3 4 5 6 7 8 9]
Into
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


arr[n]: return the nth row of arr

arr[n,m]: return the element at mth and nth position

In [13]:
secondRow=reshape1[2]
print(secondRow)

nthElement=reshape[2,2]
print(nthElement)

[4 5]
9


Slicing Rows:

arr[n:m]: slice the array, it returns a new array starting from the nth row, reaching the m-1 row

default value of n: 0

default value of m: size of list

In [14]:
print('slice from row at index 1 till row at index 3')
print(reshape1[1:4])

print('slice from row at index 0 till row at index 1')
print(reshape[:2])


print('slice from row at index 1 till the last row')
print(reshape[1:])

print('same as without slicing, returns the whole array')
print(reshape[:])

slice from row at index 1 till row at index 3
[[2 3]
 [4 5]
 [6 7]]
slice from row at index 0 till row at index 1
[[1 2 3]
 [4 5 6]]
slice from row at index 1 till the last row
[[4 5 6]
 [7 8 9]]
same as without slicing, returns the whole array
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Accessing Columns

arr[n:m, k]: returns the sliced rows  from n to m positined at the kth column.


In [15]:
print(reshape1)
print('access elements from row at index 1 till row at index 3 of column at index 1')
print(reshape1[1:4, 1])

print('__________________________________________________________________')

print(reshape)
print('access elements from row at index 0 till row at index 1  of column at index 2')
print(reshape[:2, 2])

print('__________________________________________________________________')

print(reshape)
print('access elements at rows of index 1 till the last row at column 0')
print(reshape[1:, 0])

print('__________________________________________________________________')

print(reshape)
print(' returns all elements of the rows at column 1 ')
print(reshape[:, 1])

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
access elements from row at index 1 till row at index 3 of column at index 1
[3 5 7]
__________________________________________________________________
[[1 2 3]
 [4 5 6]
 [7 8 9]]
access elements from row at index 0 till row at index 1  of column at index 2
[3 6]
__________________________________________________________________
[[1 2 3]
 [4 5 6]
 [7 8 9]]
access elements at rows of index 1 till the last row at column 0
[4 7]
__________________________________________________________________
[[1 2 3]
 [4 5 6]
 [7 8 9]]
 returns all elements of the rows at column 1 
[2 5 8]


Accessing All Rows/Columns:

arr[n:m, y:z]:  Returns a sub-array of arr of elements positioned from row n to m and column y to z.


In [16]:

print(reshape)
print('Access elements from all rows in columns at index 1 to index 2')
print(reshape[:, 1:3]) 

print('__________________________________________________________________')

print(reshape)
print('Access elements from all rows in columns at index 0 and 2')
print(reshape[:, [0, 2]])  

print('__________________________________________________________________')

print(reshape)
print('Access the first three rows from all columns')
print(reshape[:3, :])  


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Access elements from all rows in columns at index 1 to index 2
[[2 3]
 [5 6]
 [8 9]]
__________________________________________________________________
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Access elements from all rows in columns at index 0 and 2
[[1 3]
 [4 6]
 [7 9]]
__________________________________________________________________
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Access the first three rows from all columns
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
a = np.arange(0, 18).reshape(6, 3)
b = np.arange(20, 38).reshape(6, 3)
print("Array A:\n", a)
print("Array B:\n", b)

Array A:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
Array B:
 [[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]


Basic Arithmetic Operations: 

Element-wise operations: +, -, *, /

np.add(a, b), np.subtract(a, b), np.multiply(a, b), np.divide(a, b)

In [18]:
print("A + B:\n", a + b)
print("np.add(A, B):\n", np.add(a, b))

print('__________________________________________________________________')

print("A - B:\n", a - b)
print("np.subtract(A, B):\n", np.subtract(a, b))

print('__________________________________________________________________')

print("A * B:\n", a * b)
print("np.multiply(A, B):\n", np.multiply(a, b))

print('__________________________________________________________________')

print("A / B:\n", a / b)
print("np.divide(A, B):\n",np.divide(a, b))


A + B:
 [[20 22 24]
 [26 28 30]
 [32 34 36]
 [38 40 42]
 [44 46 48]
 [50 52 54]]
np.add(A, B):
 [[20 22 24]
 [26 28 30]
 [32 34 36]
 [38 40 42]
 [44 46 48]
 [50 52 54]]
__________________________________________________________________
A - B:
 [[-20 -20 -20]
 [-20 -20 -20]
 [-20 -20 -20]
 [-20 -20 -20]
 [-20 -20 -20]
 [-20 -20 -20]]
np.subtract(A, B):
 [[-20 -20 -20]
 [-20 -20 -20]
 [-20 -20 -20]
 [-20 -20 -20]
 [-20 -20 -20]
 [-20 -20 -20]]
__________________________________________________________________
A * B:
 [[  0  21  44]
 [ 69  96 125]
 [156 189 224]
 [261 300 341]
 [384 429 476]
 [525 576 629]]
np.multiply(A, B):
 [[  0  21  44]
 [ 69  96 125]
 [156 189 224]
 [261 300 341]
 [384 429 476]
 [525 576 629]]
__________________________________________________________________
A / B:
 [[0.         0.04761905 0.09090909]
 [0.13043478 0.16666667 0.2       ]
 [0.23076923 0.25925926 0.28571429]
 [0.31034483 0.33333333 0.35483871]
 [0.375      0.39393939 0.41176471]
 [0.42857143 0.4444444

Matrix Multiplication (Dot Product)

np.dot(a, b.T) or a.dot(b.T) (when compatible shapes)

In [19]:

b = b.reshape(3, 6)
print("Dot product of A and reshaped B:\n", np.dot(a, b))


Dot product of A and reshaped B:
 [[  90   93   96   99  102  105]
 [ 324  336  348  360  372  384]
 [ 558  579  600  621  642  663]
 [ 792  822  852  882  912  942]
 [1026 1065 1104 1143 1182 1221]
 [1260 1308 1356 1404 1452 1500]]


Statistical Operations

.max(), .min(), .argmax(), .argmin(), .sum(), .mean(), .std()

In [20]:
print("Max of B:", b.max())
print("Min of B:", b.min())
print("Index of Max of B:", b.argmax())
print("Sum of elements in B:", b.sum())
print("Mean of elements in B:", b.mean())
print("Standard deviation of B:", b.std())


Max of B: 37
Min of B: 20
Index of Max of B: 17
Sum of elements in B: 513
Mean of elements in B: 28.5
Standard deviation of B: 5.188127472091127


Axis-Specific Summations

np.sum(b, axis=1): Sum along rows.

np.sum(b, axis=0): Sum along columns.

In [21]:
print("Sum along rows of B:\n", np.sum(b, axis=1))
print("Sum along columns of B:\n", np.sum(b, axis=0))

Sum along rows of B:
 [135 171 207]
Sum along columns of B:
 [78 81 84 87 90 93]


Element-wise Mathematical Functions

np.sqrt(b): Square root.

np.log(b): Logarithm.

In [22]:
print("Square root of elements in B:\n", np.sqrt(b))
print("Log of elements in B:\n", np.log(b))

Square root of elements in B:
 [[4.47213595 4.58257569 4.69041576 4.79583152 4.89897949 5.        ]
 [5.09901951 5.19615242 5.29150262 5.38516481 5.47722558 5.56776436]
 [5.65685425 5.74456265 5.83095189 5.91607978 6.         6.08276253]]
Log of elements in B:
 [[2.99573227 3.04452244 3.09104245 3.13549422 3.17805383 3.21887582]
 [3.25809654 3.29583687 3.33220451 3.36729583 3.40119738 3.4339872 ]
 [3.4657359  3.49650756 3.52636052 3.55534806 3.58351894 3.61091791]]


In [23]:

angles_degrees = np.array([0, 30, 45, 60, 90])
angles_radians = np.radians(angles_degrees) 
print("Angles in radians:", angles_radians)

Angles in radians: [0.         0.52359878 0.78539816 1.04719755 1.57079633]


Basic Trigonometric Functions

In [24]:

sin_values = np.sin(angles_radians)
cos_values = np.cos(angles_radians)
tan_values = np.tan(angles_radians)

print("Angles in radians:", angles_radians)
print("Sine values:", sin_values)
print("Cosine values:", cos_values)
print("Tangent values:", tan_values)


Angles in radians: [0.         0.52359878 0.78539816 1.04719755 1.57079633]
Sine values: [0.         0.5        0.70710678 0.8660254  1.        ]
Cosine values: [1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]
Tangent values: [0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


Hyperbolic Trigonometric Functions

In [25]:

sinh_values = np.sinh(angles_radians)
cosh_values = np.cosh(angles_radians)
tanh_values = np.tanh(angles_radians)

print("Sinh values:", sinh_values)
print("Cosh values:", cosh_values)
print("Tanh values:", tanh_values)


Sinh values: [0.         0.54785347 0.86867096 1.24936705 2.3012989 ]
Cosh values: [1.         1.14023832 1.32460909 1.60028686 2.50917848]
Tanh values: [0.         0.48047278 0.6557942  0.78071444 0.91715234]


Radian to Degree Conversion and Vice Versa

In [26]:

angles_in_degrees = np.degrees(angles_radians)
angles_in_radians = np.radians(angles_degrees)

print("Angles in degrees:", angles_in_degrees)
print("Angles in radians:", angles_in_radians)


Angles in degrees: [ 0. 30. 45. 60. 90.]
Angles in radians: [0.         0.52359878 0.78539816 1.04719755 1.57079633]


Basic Random Number Generators

np.random.random(): generates a random float between 0 and 1. Each time it is called, a new random value is produced.

np.random.random(s): Generates an array of size s with random float elements between 0 and 1.

np.random.random((mxn)): generates a mxn array  of random floats between 0 and 1.


In [27]:
print('random float: ',  np.random.random())

print('random 1D array of floats of size 2')
r1=np.random.random(2)  
print(r1)

print('random 2D array of floats of size 2x3')
r2=np.random.random((2, 3))  
print(r2)

random float:  0.6550488517933034
random 1D array of floats of size 2
[0.38655662 0.35629231]
random 2D array of floats of size 2x3
[[0.17492405 0.57085757 0.00547181]
 [0.05615925 0.5039185  0.30839232]]


Random Integers

np.random.randint(low, high): 

generates a random integer within the specified range (low, high), each time  you call the function, it return  a different integer.


np.random.randint(low, high, size)
Generates an array of random integers within the specified range with the given size.

In [28]:
r=np.random.randint(1,10)
print(r)

np.random.randint(1, 10, (2, 2))  # 2x2 array of random integers between 1 and 10
np.random.randint(1, 10, (2, 2, 2))  # 3D array


6


array([[[5, 5],
        [9, 7]],

       [[9, 1],
        [3, 7]]], dtype=int32)

np.random.choice(array)

Randomly selects a single value from the specified array.

In [29]:
array = np.arange(1, 11) 
print(array)
np.random.choice(array)

[ 1  2  3  4  5  6  7  8  9 10]


np.int64(2)

Concatenate Strings

np.char.add allows you to concatenate two strings element-wise in NumPy.



In [30]:
s1 = "Welcome to"
s2 = "Python Course"

result = np.char.add(s1, s2)
print(result)


Welcome toPython Course


Convert to Uppercase

np.char.upper changes all characters in a string to uppercase.

In [31]:

upper_case = np.char.upper(s1)
print(upper_case)


WELCOME TO


 Convert to Lowercase
 
np.char.lower changes all characters in a string to lowercase.

In [32]:

lower_case = np.char.lower(s1)
print(lower_case)


welcome to


Split the String at Spaces

np.char.split splits a string into a list at each whitespace.

In [33]:

split_str = np.char.split(s1)
print(split_str)


['Welcome', 'to']


Split at New Lines

np.char.splitlines splits a string at each newline character.

In [34]:
s1_multiline = "Fatima is my\nname"

split_lines = np.char.splitlines(s1_multiline)
print(split_lines)


['Fatima is my', 'name']


Replace Substring

np.char.replace replaces one substring with another within a string.

In [35]:

replace_name = np.char.replace(s2, "Python", "AI")
print(replace_name)


AI Course


 Center Text with Padding Character
 
np.char.center centers a string in a specified width and fills the space around it with a chosen character.

In [39]:

centered_text = np.char.center("Goodbye", 40, fillchar="*")
print(centered_text)


****************Goodbye*****************
